name: tender_touch
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2002

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1 #to use svg pictures
  cupertino_icons: ^1.0.6 #app icon
  page_transition: ^2.0.5 #used for smooth page transition
  http: ^1.2.1 #launch links
  url_launcher: ^6.0.12 #launch url
  flutter_custom_clippers: ^2.1.0 #used for special design
  file_picker: ^4.0.0 #file picker for images
  carousel_slider: ^4.2.1 #carousel package
  image_picker: ^0.8.6+1 #pick image for phones
  flutter_secure_storage: ^5.0.2 #store the token after login
  jwt_decode: ^0.3.0 #token and userid transfer
  permission_handler: ^10.0.0 #for permission
  open_app_settings: ^2.0.1 #open settings for permission
  shared_preferences: ^2.0.17 #to update user's info
  mime: ^1.0.4 #for image upload to the database

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.webp"


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/Images/
    - images/icons/
    - images/home_images/
    - images/slider/
    - images/menubuttons/
    - images/onboarding/
    - images/emergency/
    - images/places/
    - images/home_images/male_avatar.jpg
    - images/home_images/female_avatar.jpg





